<a href="https://colab.research.google.com/github/Sakshipingale13/DSBDA-Practical/blob/main/DSBDA_A6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset. 2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.


In [ ]:
# Import the essential packages
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [ ]:
data=sns.load_dataset("iris") # Load iris dataset

In [ ]:
data.describe()   # Basic stats

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
data.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# Splitting dataset into features and target variable
x = data.drop('species', axis=1)
y = data['species']

In [ ]:
 #  dividing the dataset in two datasets one for train and one for test
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=42)

Model Building

In [ ]:
 # model declaration
model = GaussianNB()   # Naive Bayes classifier

In [ ]:
# Train the model on the training data
model.fit(xtrain, ytrain)

GaussianNB()

In [ ]:
Score=model.score(xtest,ytest)
print(Score)

0.9777777777777777


In [ ]:
# Predicting the class labels
y_pred = model.predict(xtest)

In [ ]:
# Confusion matrix
conf_matrix = confusion_matrix(ytest, y_pred)
print(conf_matrix)

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [ ]:
# True Positives, False Positives, True Negatives, False Negatives
print(f"TP value is  {conf_matrix[1][1]}")
FP = conf_matrix[0, 1]
TN = conf_matrix[0, 0]
FN = conf_matrix[1, 0]

TP value is  12


In [ ]:
accuracy = accuracy_score(ytest, y_pred)  # Accuracy
print("Accuracy:", accuracy)


Accuracy: 0.9777777777777777


In [ ]:
error_rate = 1 - accuracy              # Error Rate
print("Error Rate:", error_rate)

Error Rate: 0.022222222222222254


In [ ]:
precision = precision_score(ytest, y_pred, average='macro')       # Precision
print("Precision:", precision)


Precision: 0.9761904761904763


In [ ]:
recall = recall_score(ytest, y_pred, average='macro')            # Recall
print("Recall:", recall)

Recall: 0.9743589743589745
